/**
 * The shape of src/data/levels.json, which is generated by tools/gen_levels.py
 * and never edited by hand. Python owns every number in this lesson; this file
 * is the contract the UI reads it through.
 */

export type Outcome = 'hit' | 'fill' | 'evict'

export type Policy = 'fifo' | 'lru' | 'clock' | 'opt'

/** One tick of the tape under some reference policy. */
export interface Step {
  /** 1-based position on the tape. */
  step: number
  page: number
  outcome: Outcome
  /** The frame index holding `page` after this request. */
  slot: number
  /** The page thrown out, if any. */
  victim: number | null
  /** Frame contents after this request; `null` is an empty slot. */
  frames: (number | null)[]
  /** Use bits after this request. Present on clock traces only. */
  bits?: number[]
  /**
   * 1-based tape position where `victim` is next requested, or `null` if it
   * never is. Present on OPT evictions only — screen 8 draws this.
   */
  victim_next_use?: number | null
}

export interface Scores {
  fifo: number
  lru: number
  /** Least frequently used: the 'I counted how often' answer on screen 5. */
  lfu: number
  clock: number
  opt: number
  /** Clock that rescans from slot 0 every time: the learner who clears bits but keeps no state. */
  clockNoHand: number
  /** "When every bit is 1, clear them all": the other natural first attempt. */
  clearAll: number
  /** Mean faults of a uniformly random evictor — the "mostly guessing" row. */
  randomAvg: number
}

export interface Level {
  name: 'l1' | 'l2' | 'l3'
  title: string
  ref: number[]
  frames: number
  pages: number[]
  length: number
  scores: Scores
  traces: Partial<Record<Policy, Step[]>>
}

export interface BeladyRun {
  small: { frames: number; faults: number; steps: Step[] }
  big: { frames: number; faults: number; steps: Step[] }
  /** 1-based steps where the small memory holds a page the big one has dropped. */
  leakSteps: number[]
}

export interface LevelData {
  generatedBy: string
  levels: Record<'l1' | 'l2' | 'l3', Level>
  belady: {
    ref: number[]
    pages: number[]
    length: number
    runs: Record<Policy, BeladyRun>
  }
}

/**
 * What the machine's face displays. The rest of the app knows these six words
 * and nothing about what is drawn for them — see setMachineState.
 */
export type MachineState =
  | 'neutral'
  | 'approval'
  | 'correction'
  | 'smug'
  | 'apologetic'
  | 'withholding'

/**
 * Screen 5: what the learner says they were doing, tested on screen 7.
 *
 * Four options, four different measurable things: time since last use, arrival
 * order, total number of uses, and nothing. An earlier set had two options that
 * pointed at the same page ("hadn't touched in a while" and "could remember
 * least about") and one that was ambiguous between two policies ("sitting there
 * longest" reads as both arrival order and idle time), which meant screen 7
 * could test a rule the learner had not meant.
 */
export type DeclaredRule = 'lru' | 'fifo' | 'lfu' | 'random'
