/**
 * The shape of src/data/levels.json, which is generated by tools/gen_levels.py
 * and never edited by hand. Python owns every number in this lesson; this file
 * is the contract the UI reads it through.
 */

export type Outcome = 'hit' | 'fill' | 'evict'

export type Policy = 'fifo' | 'lru' | 'lfu' | 'clock' | 'opt'

/** One tick of the tape under some reference policy. */
export interface Step {
  /** 1-based position on the tape. */
  step: number
  page: number
  outcome: Outcome
  /** The frame index holding `page` after this request. */
  slot: number
  /** The page thrown out, if any. */
  victim: number | null
  /** Frame contents after this request; `null` is an empty slot. */
  frames: (number | null)[]
  /** Use bits after this request. Present on clock traces only. */
  bits?: number[]
  /**
   * 1-based tape position where `victim` is next requested, or `null` if it
   * never is. Present on OPT evictions only — screen 8 draws this.
   */
  victim_next_use?: number | null
}

/** Clock's recorded actions, in the order the UI must show them. */
export interface ClockStep extends Step {
  /** Reference bits after this request, one per frame. */
  bits: number[]
  /** 0-based position of the persistent hand before this request. */
  handBefore: number
  /**
   * 0-based slots inspected, including the final zero-bit victim. A skipped
   * one-bit slot is cleared when inspected. Empty on hits and initial fills.
   * An all-ones memory can revisit the first slot: [0, 1, 2, 0].
   */
  scanned: number[]
  /** Next search starts here; unchanged on hits and initial fills. */
  handAfter: number
}

export type PolicyStep<P extends Policy> = P extends 'clock' ? ClockStep : Step
export type PolicyTraces = { [P in Policy]?: PolicyStep<P>[] }

export interface Scores {
  fifo: number
  lru: number
  /** Least frequently used: the 'I counted how often' answer on screen 5. */
  lfu: number
  clock: number
  opt: number
  /** Clock that rescans from slot 0 every time: the learner who clears bits but keeps no state. */
  clockNoHand: number
  /** "When every bit is 1, clear them all": the other natural first attempt. */
  clearAll: number
  /** Mean faults of a uniformly random evictor — the "mostly guessing" row. */
  randomAvg: number
}

/**
 * The first eviction on a tape where the three past-looking signals disagree.
 *
 * Screen 7 replays this fork and only then reveals `nextUse`. The numbers are
 * sim.first_signal_fork's, not the interface's: which page each rule points at
 * is exactly the kind of figure the front end must never re-derive.
 */
export interface Fork {
  /** 1-based tape position of the eviction. */
  step: number
  /** The page being requested when memory was full. */
  request: number
  /** Resident pages at that moment. */
  mem: number[]
  /** The page each signal would evict. */
  fifo: number
  lru: number
  lfu: number
  /** Page -> 1-based step where it is next requested, or null if never again. */
  nextUse: Record<string, number | null>
}

/**
 * One eviction on a tape played with the whole future visible.
 *
 * Screen 8 is the learner replaying level 1 face up, and at a fork like this
 * every option has an answer printed on the tape: the step that page comes back
 * on, or nothing at all if it never does. That is what lets a wrong tap be
 * refused with a fact rather than a nudge, and the fact is
 * sim.face_up_decisions', not the interface's.
 */
export interface Decision {
  /** 1-based tape position of the eviction. */
  step: number
  /** The page arriving to a full memory. */
  request: number
  /** Resident pages at that moment. */
  mem: number[]
  /** Page -> 1-based step where it is next requested, or null if never again. */
  nextUse: Record<string, number | null>
  /** The page whose next use is farthest away: the only tap that executes. */
  victim: number
}

/**
 * Why the best score on a tape is the best score, in the two parts screen 8
 * puts on the tape rather than in a bubble.
 *
 * A floor asserted by a tutor is a number to believe. These are the facts it is
 * built from: every distinct page has to enter once, and the request that finds
 * memory full forces one more whenever every page it could displace is asked
 * for again. `atLeast` is the bound; it is only *the floor* because `achieved`,
 * which is what the learner scores, reaches it.
 */
export interface Floor {
  /** Page -> the 1-based step it is first requested on. One fault each. */
  firstUses: Record<string, number>
  /** How many pages must enter: the cold misses nobody can avoid. */
  unavoidable: number
  /** The first request that arrives with memory full, or null if none does. */
  forcedStep: number | null
  forcedRequest: number | null
  /** What was resident then, and when each of them is asked for again. */
  resident: number[]
  residentNextUse: Record<string, number | null>
  /** The bound the two facts add up to, and the count OPT actually reaches. */
  atLeast: number
  achieved: number
}

export interface Level {
  name: 'l1' | 'l2' | 'l3'
  title: string
  ref: number[]
  frames: number
  pages: number[]
  length: number
  scores: Scores
  traces: PolicyTraces
  /** Null on tapes whose first eviction is not diagnostic. */
  fork: Fork | null
  /** Every fork of a face-up replay, in order. Screen 8 plays L1's two. */
  decisions: Decision[]
  floor: Floor
}

export interface BeladyRun<P extends Policy = Policy> {
  small: { frames: number; faults: number; steps: PolicyStep<P>[] }
  big: { frames: number; faults: number; steps: PolicyStep<P>[] }
  /** 1-based steps where the small memory holds a page the big one has dropped. */
  leakSteps: number[]
}

export interface LevelData {
  generatedBy: string
  transfer: {
    capacity: number
    taskA: string[]
    taskB: string[]
    /** Zero-based pairs of observed requests showing quick returns. */
    shortReturns: [number, number][]
    cycleLength: number
    checkpoint: {
      requestIndex: number
      resident: string[]
      incoming: string
      victim: string
      nextIndices: number[]
    }
  }
  clockQuickCheck: {
    initialFrames: number[]
    initialBits: number[]
    ref: number[]
    steps: ClockStep[]
  }
  recencyDemo: {
    frames: number[]
    snapshots: { step: number; page: number; lastUsed: number[] }[]
  }
  levels: Record<'l1' | 'l2' | 'l3', Level>
  belady: {
    ref: number[]
    pages: number[]
    length: number
    runs: { [P in Policy]: BeladyRun<P> }
  }
}

/**
 * What the machine's face displays. The rest of the app knows these six words
 * and nothing about what is drawn for them — see setMachineState.
 */
export type MachineState =
  | 'neutral'
  | 'approval'
  | 'correction'
  | 'satisfied'
  | 'apologetic'
  | 'withholding'

/**
 * Screen 5: what the learner says they were doing, held to it on screen 6.
 *
 * Four options, four different measurable things: time since last use, time in
 * memory, total number of uses, and nothing. An earlier set had two options
 * that pointed at the same page ("hadn't touched in a while" and "could
 * remember least about") and one that was ambiguous between two policies
 * ("sitting there longest" reads as both arrival order and idle time), which
 * meant screen 6 could hold the learner to a rule they had not meant.
 */
export type DeclaredRule = 'lru' | 'fifo' | 'lfu' | 'random'
